name: delete Roboshop infrastructure

on: [workflow_dispatch]

jobs:

  DEV-APPLY:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform init -backend-config=env-dev/state.tfvars
      - name: Terraform destroy
        run: terraform destroy -var-file=env-dev/main.tfvars -auto-approve -var vault_token ${{ secrets.Vault_token }}





  # PROD:
  #  runs-on: self-hosted
  #  environment: prod
  #  needs: UAT
  #  steps:
  #    - uses: actions/checkout@v4
  #    - name: Terraform Init for PROD
  #      run: terraform init
